---
title: "Kalman Interpolation"
author: "Marco Milli"
output: html_notebook
---

## Install RcppArmadillo for required impute libraries
### System GCC incompatible with current RcppArmadillo library, an update of the gcc was denied by OS, so an older version of the library had to be installed....

``` 
install.packages("https://cran.r-project.org/src/contrib/Archive/RcppArmadillo/RcppArmadillo_0.6.100.0.0.tar.gz",repos=NULL, type="source") 
install.packages('forecast')

install.packages('imputeTS')
```


```{r libs}
library(tidyr)
library(plyr)
library(stringr)
library(lubridate)
library(MASS)
library(zoo)
library(broom)
library(knitr)
library(imputeTS)
library(glue)
library(readr)

```




```{r}

datapath ='/Users/marco/projects/data_science/marco-folder/final_project_swiss/swiss-bise-project/01_data/weather_data_for_interpolation.csv'


df <- read_csv(datapath)
df

```




```{r}
cat('Total Nas in weather data:', sum(is.na(df)))
which(is.na(data))
```


```{r}
colSums(is.na(df)) / nrow(df) * 100
```


```{r}
plotNA.distribution(ts(df$Air_temp), pch = 20, cexPoints = 0)
```


```{r}
imp <- na_kalman(ts(df$Air_temp))
plotNA.imputations(ts(df$Air_temp), imp, cex = 0)
```


```{r}
imp
```

```{r}
lengths(df)
```


```{r}
print(ncol(df))
#ls("package:MASS")
df %>% dplyr::select(1:3)

```
```{r}
colSums(is.na(df)) / nrow(df) * 100
```


```
kalman_fix <- function(x) {
  temp_K <- ((temp_F - 32) * (5 / 9)) + 273.15
  return(temp_K)
}
```

```{r}
getwd()
```





```{r}
df_kal <- apply(df %>% dplyr::select(4:ncol(df)), 2, function(x) na_kalman(x, type="level"))  
# Merging the matrix with the first two columns of the original df
df_kal_df = cbind((df %>% dplyr::select(1:3)), data.frame(df_kal))

df_kal_df
```


```{r}
colSums(is.na(df_kal_df)) / nrow(df_kal_df) * 100
```
```{r}
print(min(df_kal_df$Wind_dir))
```

```{r}
write.table(df_kal_df, "/Users/marco/projects/data_science/marco-folder/final_project_swiss/swiss-bise-project/01_data/weather_data_with_interpolation.csv", sep=",")
```

<h1>Working on other dataset</h1>



```{r}

datapath2 ='/Users/marco/projects/data_science/marco-folder/final_project_swiss/swiss-bise-project/01_data/weather_selected_stations.csv'

df2 <- read_csv(datapath2)
df2
```
